// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClkyAij5VlWkk_ohHxPK6VxpZIPT1D0tw',
    appId: '1:769471668045:web:1a6bd5283be996ef492104',
    messagingSenderId: '769471668045',
    projectId: 'amam-job-seeking',
    authDomain: 'amam-job-seeking.firebaseapp.com',
    storageBucket: 'amam-job-seeking.appspot.com',
    measurementId: 'G-06ZWC13TCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhPw-Z7trZ7hoiZYMFY18PGaJjEEhnLE',
    appId: '1:769471668045:android:8e3d82f400427b42492104',
    messagingSenderId: '769471668045',
    projectId: 'amam-job-seeking',
    storageBucket: 'amam-job-seeking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_qnPx4QA4-4J00XOfw-oydzU5u2XMyR8',
    appId: '1:769471668045:ios:35de44d68de3a736492104',
    messagingSenderId: '769471668045',
    projectId: 'amam-job-seeking',
    storageBucket: 'amam-job-seeking.appspot.com',
    iosBundleId: 'com.ziad.amamJobSeekerAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_qnPx4QA4-4J00XOfw-oydzU5u2XMyR8',
    appId: '1:769471668045:ios:50cfca0975abdad1492104',
    messagingSenderId: '769471668045',
    projectId: 'amam-job-seeking',
    storageBucket: 'amam-job-seeking.appspot.com',
    iosBundleId: 'com.ziad.amamJobSeekerAssessment.RunnerTests',
  );
}
